/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const scopeEnum = {
  Connection: "Connection",
  Statement: "Statement",
} as const;

export type ScopeEnumKey = (typeof scopeEnum)[keyof typeof scopeEnum];

export type Scope = ScopeEnumKey;

export type Claims = {
  /**
   * @minLength 0
   * @type integer
   */
  exp: number;
  /**
   * @type string
   */
  scope: Scope;
  /**
   * @type string
   */
  sub: string;
};

export type CreateConnectionRequest = {
  /**
   * @type object | undefined
   */
  options?: {
    [key: string]: string;
  };
};

export type CreateConnectionResponse = {
  /**
   * @type string
   */
  token: string;
};

export type CreateDatabaseRequest = {
  /**
   * @type string
   */
  driver: string;
  /**
   * @type object | undefined
   */
  options?: {
    [key: string]: string;
  };
};

export type CreateDatabaseResponse = {
  /**
   * @type string
   */
  id: string;
};

export type CreateStatementResponse = {
  /**
   * @type string
   */
  token: string;
};

export type DatabaseInfo = {
  /**
   * @type string
   */
  driver_name: string;
  /**
   * @type string
   */
  id: string;
};

export type QueryRequest = {
  /**
   * @type string
   */
  query: string;
};

export type SetOptionRequest = {
  /**
   * @type string
   */
  key: string;
  /**
   * @type string
   */
  value: string;
};

export type SetSqlQueryRequest = {
  /**
   * @type string
   */
  query: string;
};

/**
 * @description Connection released
 */
export type DeleteConnection204 = any;

/**
 * @description Connection not found
 */
export type DeleteConnection404 = any;

export type DeleteConnectionMutationResponse = DeleteConnection204;

export type DeleteConnectionMutation = {
  Response: DeleteConnection204;
  Errors: DeleteConnection404;
};

/**
 * @description Operation cancelled
 */
export type CancelConnection204 = any;

/**
 * @description Connection not found
 */
export type CancelConnection404 = any;

/**
 * @description Failed to cancel operation
 */
export type CancelConnection500 = any;

export type CancelConnectionMutationResponse = CancelConnection204;

export type CancelConnectionMutation = {
  Response: CancelConnection204;
  Errors: CancelConnection404 | CancelConnection500;
};

/**
 * @description Transaction committed
 */
export type CommitConnection204 = any;

/**
 * @description Connection not found
 */
export type CommitConnection404 = any;

/**
 * @description Failed to commit transaction
 */
export type CommitConnection500 = any;

export type CommitConnectionMutationResponse = CommitConnection204;

export type CommitConnectionMutation = {
  Response: CommitConnection204;
  Errors: CommitConnection404 | CommitConnection500;
};

/**
 * @description Database metadata info
 */
export type GetConnectionInfo200 = Blob;

/**
 * @description Connection not found
 */
export type GetConnectionInfo404 = any;

export type GetConnectionInfoQueryResponse = GetConnectionInfo200;

export type GetConnectionInfoQuery = {
  Response: GetConnectionInfo200;
  Errors: GetConnectionInfo404;
};

export type GetConnectionObjectsQueryParams = {
  /**
   * @minLength 0
   * @type integer, int32
   */
  depth?: number | null;
  /**
   * @type string
   */
  catalog?: string | null;
  /**
   * @type string
   */
  db_schema?: string | null;
  /**
   * @type string
   */
  table_name?: string | null;
  /**
   * @type array
   */
  table_type?: string[] | null;
  /**
   * @type string
   */
  column_name?: string | null;
};

/**
 * @description Database objects
 */
export type GetConnectionObjects200 = Blob;

/**
 * @description Connection not found
 */
export type GetConnectionObjects404 = any;

export type GetConnectionObjectsQueryResponse = GetConnectionObjects200;

export type GetConnectionObjectsQuery = {
  Response: GetConnectionObjects200;
  QueryParams: GetConnectionObjectsQueryParams;
  Errors: GetConnectionObjects404;
};

/**
 * @description Option set
 */
export type SetConnectionOption204 = any;

/**
 * @description Connection not found
 */
export type SetConnectionOption404 = any;

/**
 * @description Failed to set option
 */
export type SetConnectionOption500 = any;

export type SetConnectionOptionMutationRequest = SetOptionRequest;

export type SetConnectionOptionMutationResponse = SetConnectionOption204;

export type SetConnectionOptionMutation = {
  Response: SetConnectionOption204;
  Request: SetConnectionOptionMutationRequest;
  Errors: SetConnectionOption404 | SetConnectionOption500;
};

/**
 * @description Arrow IPC Stream
 */
export type QueryConnectionIpc200 = Blob;

/**
 * @description Connection not found
 */
export type QueryConnectionIpc404 = any;

/**
 * @description Failed to execute query
 */
export type QueryConnectionIpc500 = any;

export type QueryConnectionIpcMutationRequest = QueryRequest;

export type QueryConnectionIpcMutationResponse = QueryConnectionIpc200;

export type QueryConnectionIpcMutation = {
  Response: QueryConnectionIpc200;
  Request: QueryConnectionIpcMutationRequest;
  Errors: QueryConnectionIpc404 | QueryConnectionIpc500;
};

/**
 * @description Transaction rolled back
 */
export type RollbackConnection204 = any;

/**
 * @description Connection not found
 */
export type RollbackConnection404 = any;

/**
 * @description Failed to rollback transaction
 */
export type RollbackConnection500 = any;

export type RollbackConnectionMutationResponse = RollbackConnection204;

export type RollbackConnectionMutation = {
  Response: RollbackConnection204;
  Errors: RollbackConnection404 | RollbackConnection500;
};

/**
 * @description Statement created
 */
export type CreateStatement200 = CreateStatementResponse;

/**
 * @description Connection not found
 */
export type CreateStatement404 = any;

/**
 * @description Failed to create statement
 */
export type CreateStatement500 = any;

export type CreateStatementMutationResponse = CreateStatement200;

export type CreateStatementMutation = {
  Response: CreateStatement200;
  Errors: CreateStatement404 | CreateStatement500;
};

/**
 * @description Table types
 */
export type GetConnectionTableTypes200 = Blob;

/**
 * @description Connection not found
 */
export type GetConnectionTableTypes404 = any;

export type GetConnectionTableTypesQueryResponse = GetConnectionTableTypes200;

export type GetConnectionTableTypesQuery = {
  Response: GetConnectionTableTypes200;
  Errors: GetConnectionTableTypes404;
};

export type GetConnectionTableSchemaPathParams = {
  /**
   * @description Table Name
   * @type string
   */
  table_name: string;
};

export type GetConnectionTableSchemaQueryParams = {
  /**
   * @type string
   */
  catalog?: string | null;
  /**
   * @type string
   */
  db_schema?: string | null;
};

/**
 * @description Table schema
 */
export type GetConnectionTableSchema200 = Blob;

/**
 * @description Connection not found
 */
export type GetConnectionTableSchema404 = any;

export type GetConnectionTableSchemaQueryResponse = GetConnectionTableSchema200;

export type GetConnectionTableSchemaQuery = {
  Response: GetConnectionTableSchema200;
  PathParams: GetConnectionTableSchemaPathParams;
  QueryParams: GetConnectionTableSchemaQueryParams;
  Errors: GetConnectionTableSchema404;
};

/**
 * @description List active databases
 */
export type ListDatabases200 = DatabaseInfo[];

export type ListDatabasesQueryResponse = ListDatabases200;

export type ListDatabasesQuery = {
  Response: ListDatabases200;
  Errors: any;
};

/**
 * @description Database created successfully
 */
export type CreateDatabase200 = CreateDatabaseResponse;

/**
 * @description Bad Request
 */
export type CreateDatabase400 = any;

/**
 * @description Internal Server Error
 */
export type CreateDatabase500 = any;

export type CreateDatabaseMutationRequest = CreateDatabaseRequest;

export type CreateDatabaseMutationResponse = CreateDatabase200;

export type CreateDatabaseMutation = {
  Response: CreateDatabase200;
  Request: CreateDatabaseMutationRequest;
  Errors: CreateDatabase400 | CreateDatabase500;
};

export type DeleteDatabasePathParams = {
  /**
   * @description Database ID to delete
   * @type string
   */
  id: string;
};

/**
 * @description Database deleted
 */
export type DeleteDatabase204 = any;

/**
 * @description Database not found
 */
export type DeleteDatabase404 = any;

export type DeleteDatabaseMutationResponse = DeleteDatabase204;

export type DeleteDatabaseMutation = {
  Response: DeleteDatabase204;
  PathParams: DeleteDatabasePathParams;
  Errors: DeleteDatabase404;
};

export type CreateConnectionPathParams = {
  /**
   * @description Database ID to acquire connection from
   * @type string
   */
  id: string;
};

/**
 * @description Connection acquired successfully
 */
export type CreateConnection200 = CreateConnectionResponse;

/**
 * @description Database not found
 */
export type CreateConnection404 = any;

/**
 * @description Failed to acquire connection
 */
export type CreateConnection500 = any;

export type CreateConnectionMutationRequest = CreateConnectionRequest | null;

export type CreateConnectionMutationResponse = CreateConnection200;

export type CreateConnectionMutation = {
  Response: CreateConnection200;
  Request: CreateConnectionMutationRequest;
  PathParams: CreateConnectionPathParams;
  Errors: CreateConnection404 | CreateConnection500;
};

/**
 * @description List available drivers
 */
export type ListDrivers200 = string[];

export type ListDriversQueryResponse = ListDrivers200;

export type ListDriversQuery = {
  Response: ListDrivers200;
  Errors: any;
};

/**
 * @description Health check passed
 */
export type HealthCheck200 = string;

export type HealthCheckQueryResponse = HealthCheck200;

export type HealthCheckQuery = {
  Response: HealthCheck200;
  Errors: any;
};

/**
 * @description Statement released
 */
export type DeleteStatement204 = any;

/**
 * @description Statement not found
 */
export type DeleteStatement404 = any;

export type DeleteStatementMutationResponse = DeleteStatement204;

export type DeleteStatementMutation = {
  Response: DeleteStatement204;
  Errors: DeleteStatement404;
};

/**
 * @description Parameters bound
 */
export type BindStatement204 = any;

/**
 * @description Statement not found
 */
export type BindStatement404 = any;

/**
 * @description Failed to bind parameters
 */
export type BindStatement500 = any;

export type BindStatementMutationRequest = Blob;

export type BindStatementMutationResponse = BindStatement204;

export type BindStatementMutation = {
  Response: BindStatement204;
  Request: BindStatementMutationRequest;
  Errors: BindStatement404 | BindStatement500;
};

/**
 * @description Query executed
 */
export type ExecuteStatementQuery200 = Blob;

/**
 * @description Statement not found
 */
export type ExecuteStatementQuery404 = any;

/**
 * @description Failed to execute query
 */
export type ExecuteStatementQuery500 = any;

export type ExecuteStatementQueryMutationResponse = ExecuteStatementQuery200;

export type ExecuteStatementQueryMutation = {
  Response: ExecuteStatementQuery200;
  Errors: ExecuteStatementQuery404 | ExecuteStatementQuery500;
};

/**
 * @description Update executed
 */
export type ExecuteStatementUpdate204 = any;

/**
 * @description Statement not found
 */
export type ExecuteStatementUpdate404 = any;

/**
 * @description Failed to execute update
 */
export type ExecuteStatementUpdate500 = any;

export type ExecuteStatementUpdateMutationResponse = ExecuteStatementUpdate204;

export type ExecuteStatementUpdateMutation = {
  Response: ExecuteStatementUpdate204;
  Errors: ExecuteStatementUpdate404 | ExecuteStatementUpdate500;
};

/**
 * @description Option set
 */
export type SetStatementOption204 = any;

/**
 * @description Statement not found
 */
export type SetStatementOption404 = any;

/**
 * @description Failed to set option
 */
export type SetStatementOption500 = any;

export type SetStatementOptionMutationRequest = SetOptionRequest;

export type SetStatementOptionMutationResponse = SetStatementOption204;

export type SetStatementOptionMutation = {
  Response: SetStatementOption204;
  Request: SetStatementOptionMutationRequest;
  Errors: SetStatementOption404 | SetStatementOption500;
};

/**
 * @description Statement prepared
 */
export type PrepareStatement204 = any;

/**
 * @description Statement not found
 */
export type PrepareStatement404 = any;

/**
 * @description Failed to prepare statement
 */
export type PrepareStatement500 = any;

export type PrepareStatementMutationResponse = PrepareStatement204;

export type PrepareStatementMutation = {
  Response: PrepareStatement204;
  Errors: PrepareStatement404 | PrepareStatement500;
};

/**
 * @description SQL query set
 */
export type SetStatementSqlQuery204 = any;

/**
 * @description Statement not found
 */
export type SetStatementSqlQuery404 = any;

/**
 * @description Failed to set SQL query
 */
export type SetStatementSqlQuery500 = any;

export type SetStatementSqlQueryMutationRequest = SetSqlQueryRequest;

export type SetStatementSqlQueryMutationResponse = SetStatementSqlQuery204;

export type SetStatementSqlQueryMutation = {
  Response: SetStatementSqlQuery204;
  Request: SetStatementSqlQueryMutationRequest;
  Errors: SetStatementSqlQuery404 | SetStatementSqlQuery500;
};
