/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const createConnectionRequestSchema = z.object({
  options: z.optional(z.object({}).catchall(z.string())),
});

export const createConnectionResponseSchema = z.object({
  token: z.string(),
});

export const createDatabaseRequestSchema = z.object({
  driver: z.string(),
  name: z.string().nullish(),
  options: z.optional(z.object({}).catchall(z.string())),
});

export const createDatabaseResponseSchema = z.object({
  id: z.string(),
});

export const createStatementResponseSchema = z.object({
  token: z.string(),
});

export const databaseInfoSchema = z.object({
  driver_name: z.string(),
  id: z.string(),
  name: z.string().nullish(),
});

export const queryRequestSchema = z.object({
  query: z.string(),
});

export const scopeSchema = z.enum(["Connection", "Statement"]);

export const setOptionRequestSchema = z.object({
  key: z.string(),
  value: z.string(),
});

export const setSqlQueryRequestSchema = z.object({
  query: z.string(),
});

/**
 * @description Connection deleted using ID from bearer token
 */
export const deleteConnection204Schema = z.any();

/**
 * @description Connection not found
 */
export const deleteConnection404Schema = z.any();

export const deleteConnectionMutationResponseSchema = z.lazy(
  () => deleteConnection204Schema,
);

/**
 * @description Operation cancelled
 */
export const cancelConnection204Schema = z.any();

/**
 * @description Connection not found
 */
export const cancelConnection404Schema = z.any();

/**
 * @description Failed to cancel operation
 */
export const cancelConnection500Schema = z.any();

export const cancelConnectionMutationResponseSchema = z.lazy(
  () => cancelConnection204Schema,
);

/**
 * @description Transaction committed
 */
export const commitConnection204Schema = z.any();

/**
 * @description Connection not found
 */
export const commitConnection404Schema = z.any();

/**
 * @description Failed to commit transaction
 */
export const commitConnection500Schema = z.any();

export const commitConnectionMutationResponseSchema = z.lazy(
  () => commitConnection204Schema,
);

/**
 * @description Database metadata info
 */
export const getConnectionInfo200Schema = z.instanceof(File);

/**
 * @description Connection not found
 */
export const getConnectionInfo404Schema = z.any();

export const getConnectionInfoQueryResponseSchema = z.lazy(
  () => getConnectionInfo200Schema,
);

export const getConnectionObjectsQueryParamsSchema = z
  .object({
    depth: z.coerce.number().int().min(0).nullish(),
    catalog: z.string().nullish(),
    db_schema: z.string().nullish(),
    table_name: z.string().nullish(),
    table_type: z.array(z.string()).nullish(),
    column_name: z.string().nullish(),
  })
  .optional();

/**
 * @description Database objects
 */
export const getConnectionObjects200Schema = z.instanceof(File);

/**
 * @description Connection not found
 */
export const getConnectionObjects404Schema = z.any();

export const getConnectionObjectsQueryResponseSchema = z.lazy(
  () => getConnectionObjects200Schema,
);

/**
 * @description Option set
 */
export const setConnectionOption204Schema = z.any();

/**
 * @description Connection not found
 */
export const setConnectionOption404Schema = z.any();

/**
 * @description Failed to set option
 */
export const setConnectionOption500Schema = z.any();

export const setConnectionOptionMutationRequestSchema = z.lazy(
  () => setOptionRequestSchema,
);

export const setConnectionOptionMutationResponseSchema = z.lazy(
  () => setConnectionOption204Schema,
);

/**
 * @description Arrow IPC Stream
 */
export const queryConnectionIpc200Schema = z.instanceof(File);

/**
 * @description Connection not found
 */
export const queryConnectionIpc404Schema = z.any();

/**
 * @description Failed to execute query
 */
export const queryConnectionIpc500Schema = z.any();

export const queryConnectionIpcMutationRequestSchema = z.lazy(
  () => queryRequestSchema,
);

export const queryConnectionIpcMutationResponseSchema = z.lazy(
  () => queryConnectionIpc200Schema,
);

/**
 * @description Transaction rolled back
 */
export const rollbackConnection204Schema = z.any();

/**
 * @description Connection not found
 */
export const rollbackConnection404Schema = z.any();

/**
 * @description Failed to rollback transaction
 */
export const rollbackConnection500Schema = z.any();

export const rollbackConnectionMutationResponseSchema = z.lazy(
  () => rollbackConnection204Schema,
);

/**
 * @description Statement created
 */
export const createStatement200Schema = z.lazy(
  () => createStatementResponseSchema,
);

/**
 * @description Connection not found
 */
export const createStatement404Schema = z.any();

/**
 * @description Failed to create statement
 */
export const createStatement500Schema = z.any();

export const createStatementMutationResponseSchema = z.lazy(
  () => createStatement200Schema,
);

/**
 * @description Table types
 */
export const getConnectionTableTypes200Schema = z.instanceof(File);

/**
 * @description Connection not found
 */
export const getConnectionTableTypes404Schema = z.any();

export const getConnectionTableTypesQueryResponseSchema = z.lazy(
  () => getConnectionTableTypes200Schema,
);

export const getConnectionTableSchemaPathParamsSchema = z.object({
  table_name: z.string().describe("Table Name"),
});

export const getConnectionTableSchemaQueryParamsSchema = z
  .object({
    catalog: z.string().nullish(),
    db_schema: z.string().nullish(),
  })
  .optional();

/**
 * @description Table schema
 */
export const getConnectionTableSchema200Schema = z.instanceof(File);

/**
 * @description Connection not found
 */
export const getConnectionTableSchema404Schema = z.any();

export const getConnectionTableSchemaQueryResponseSchema = z.lazy(
  () => getConnectionTableSchema200Schema,
);

/**
 * @description List active databases
 */
export const listDatabases200Schema = z.array(z.lazy(() => databaseInfoSchema));

export const listDatabasesQueryResponseSchema = z.lazy(
  () => listDatabases200Schema,
);

/**
 * @description Database created successfully
 */
export const createDatabase200Schema = z.lazy(
  () => createDatabaseResponseSchema,
);

/**
 * @description Bad Request
 */
export const createDatabase400Schema = z.any();

/**
 * @description Internal Server Error
 */
export const createDatabase500Schema = z.any();

export const createDatabaseMutationRequestSchema = z.lazy(
  () => createDatabaseRequestSchema,
);

export const createDatabaseMutationResponseSchema = z.lazy(
  () => createDatabase200Schema,
);

export const getDatabasePathParamsSchema = z.object({
  id: z.string().describe("Database ID to retrieve"),
});

/**
 * @description Database information
 */
export const getDatabase200Schema = z.lazy(() => databaseInfoSchema);

/**
 * @description Database not found
 */
export const getDatabase404Schema = z.any();

export const getDatabaseQueryResponseSchema = z.lazy(
  () => getDatabase200Schema,
);

export const deleteDatabasePathParamsSchema = z.object({
  id: z.string().describe("Database ID to delete"),
});

/**
 * @description Database deleted
 */
export const deleteDatabase204Schema = z.any();

/**
 * @description Database not found
 */
export const deleteDatabase404Schema = z.any();

export const deleteDatabaseMutationResponseSchema = z.lazy(
  () => deleteDatabase204Schema,
);

export const createConnectionPathParamsSchema = z.object({
  id: z.string().describe("Database ID to acquire connection from"),
});

/**
 * @description Connection acquired successfully
 */
export const createConnection200Schema = z.lazy(
  () => createConnectionResponseSchema,
);

/**
 * @description Database not found
 */
export const createConnection404Schema = z.any();

/**
 * @description Failed to acquire connection
 */
export const createConnection500Schema = z.any();

export const createConnectionMutationRequestSchema = z
  .lazy(() => createConnectionRequestSchema)
  .nullable();

export const createConnectionMutationResponseSchema = z.lazy(
  () => createConnection200Schema,
);

export const queryDatabaseIpcPathParamsSchema = z.object({
  id: z.string().describe("Database ID to query"),
});

/**
 * @description Arrow IPC Stream
 */
export const queryDatabaseIpc200Schema = z.instanceof(File);

/**
 * @description Database not found
 */
export const queryDatabaseIpc404Schema = z.any();

/**
 * @description Failed to execute query
 */
export const queryDatabaseIpc500Schema = z.any();

export const queryDatabaseIpcMutationRequestSchema = z.lazy(
  () => queryRequestSchema,
);

export const queryDatabaseIpcMutationResponseSchema = z.lazy(
  () => queryDatabaseIpc200Schema,
);

/**
 * @description List available drivers
 */
export const listDrivers200Schema = z.array(z.string());

export const listDriversQueryResponseSchema = z.lazy(
  () => listDrivers200Schema,
);

/**
 * @description Health check passed
 */
export const healthCheck200Schema = z.string();

export const healthCheckQueryResponseSchema = z.lazy(
  () => healthCheck200Schema,
);

/**
 * @description Statement released
 */
export const deleteStatement204Schema = z.any();

/**
 * @description Statement not found
 */
export const deleteStatement404Schema = z.any();

export const deleteStatementMutationResponseSchema = z.lazy(
  () => deleteStatement204Schema,
);

/**
 * @description Parameters bound
 */
export const bindStatement204Schema = z.any();

/**
 * @description Statement not found
 */
export const bindStatement404Schema = z.any();

/**
 * @description Failed to bind parameters
 */
export const bindStatement500Schema = z.any();

export const bindStatementMutationRequestSchema = z.instanceof(File);

export const bindStatementMutationResponseSchema = z.lazy(
  () => bindStatement204Schema,
);

/**
 * @description Query executed
 */
export const executeStatementQuery200Schema = z.instanceof(File);

/**
 * @description Statement not found
 */
export const executeStatementQuery404Schema = z.any();

/**
 * @description Failed to execute query
 */
export const executeStatementQuery500Schema = z.any();

export const executeStatementQueryMutationResponseSchema = z.lazy(
  () => executeStatementQuery200Schema,
);

/**
 * @description Update executed
 */
export const executeStatementUpdate204Schema = z.any();

/**
 * @description Statement not found
 */
export const executeStatementUpdate404Schema = z.any();

/**
 * @description Failed to execute update
 */
export const executeStatementUpdate500Schema = z.any();

export const executeStatementUpdateMutationResponseSchema = z.lazy(
  () => executeStatementUpdate204Schema,
);

/**
 * @description Option set
 */
export const setStatementOption204Schema = z.any();

/**
 * @description Statement not found
 */
export const setStatementOption404Schema = z.any();

/**
 * @description Failed to set option
 */
export const setStatementOption500Schema = z.any();

export const setStatementOptionMutationRequestSchema = z.lazy(
  () => setOptionRequestSchema,
);

export const setStatementOptionMutationResponseSchema = z.lazy(
  () => setStatementOption204Schema,
);

/**
 * @description Statement prepared
 */
export const prepareStatement204Schema = z.any();

/**
 * @description Statement not found
 */
export const prepareStatement404Schema = z.any();

/**
 * @description Failed to prepare statement
 */
export const prepareStatement500Schema = z.any();

export const prepareStatementMutationResponseSchema = z.lazy(
  () => prepareStatement204Schema,
);

/**
 * @description SQL query set
 */
export const setStatementSqlQuery204Schema = z.any();

/**
 * @description Statement not found
 */
export const setStatementSqlQuery404Schema = z.any();

/**
 * @description Failed to set SQL query
 */
export const setStatementSqlQuery500Schema = z.any();

export const setStatementSqlQueryMutationRequestSchema = z.lazy(
  () => setSqlQueryRequestSchema,
);

export const setStatementSqlQueryMutationResponseSchema = z.lazy(
  () => setStatementSqlQuery204Schema,
);
