/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  BindStatementMutationRequest,
  BindStatementMutationResponse,
  BindStatement404,
  BindStatement500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const bindStatementMutationKey = () =>
  [{ url: "/statements/bind" }] as const;

export type BindStatementMutationKey = ReturnType<
  typeof bindStatementMutationKey
>;

/**
 * {@link /statements/bind}
 */
export async function bindStatement(
  data?: BindStatementMutationRequest,
  config: Partial<RequestConfig<BindStatementMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    BindStatementMutationResponse,
    ResponseErrorConfig<BindStatement404 | BindStatement500>,
    BindStatementMutationRequest
  >({
    method: "POST",
    url: `/statements/bind`,
    data: requestData,
    ...requestConfig,
    headers: {
      "Content-Type": "application/octet-stream",
      ...requestConfig.headers,
    },
  });
  return res.data;
}

export function bindStatementMutationOptions(
  config: Partial<RequestConfig<BindStatementMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = bindStatementMutationKey();
  return mutationOptions<
    BindStatementMutationResponse,
    ResponseErrorConfig<BindStatement404 | BindStatement500>,
    { data?: BindStatementMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return bindStatement(data, config);
    },
  });
}

/**
 * {@link /statements/bind}
 */
export function useBindStatement<TContext>(
  options: {
    mutation?: UseMutationOptions<
      BindStatementMutationResponse,
      ResponseErrorConfig<BindStatement404 | BindStatement500>,
      { data?: BindStatementMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<BindStatementMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? bindStatementMutationKey();

  const baseOptions = bindStatementMutationOptions(
    config,
  ) as UseMutationOptions<
    BindStatementMutationResponse,
    ResponseErrorConfig<BindStatement404 | BindStatement500>,
    { data?: BindStatementMutationRequest },
    TContext
  >;

  return useMutation<
    BindStatementMutationResponse,
    ResponseErrorConfig<BindStatement404 | BindStatement500>,
    { data?: BindStatementMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    BindStatementMutationResponse,
    ResponseErrorConfig<BindStatement404 | BindStatement500>,
    { data?: BindStatementMutationRequest },
    TContext
  >;
}
