/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  CancelConnectionMutationResponse,
  CancelConnection404,
  CancelConnection500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const cancelConnectionMutationKey = () =>
  [{ url: "/connections/cancel" }] as const;

export type CancelConnectionMutationKey = ReturnType<
  typeof cancelConnectionMutationKey
>;

/**
 * {@link /connections/cancel}
 */
export async function cancelConnection(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CancelConnectionMutationResponse,
    ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
    unknown
  >({ method: "POST", url: `/connections/cancel`, ...requestConfig });
  return res.data;
}

export function cancelConnectionMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = cancelConnectionMutationKey();
  return mutationOptions<
    CancelConnectionMutationResponse,
    ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return cancelConnection(config);
    },
  });
}

/**
 * {@link /connections/cancel}
 */
export function useCancelConnection<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CancelConnectionMutationResponse,
      ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? cancelConnectionMutationKey();

  const baseOptions = cancelConnectionMutationOptions(
    config,
  ) as UseMutationOptions<
    CancelConnectionMutationResponse,
    ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
    void,
    TContext
  >;

  return useMutation<
    CancelConnectionMutationResponse,
    ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CancelConnectionMutationResponse,
    ResponseErrorConfig<CancelConnection404 | CancelConnection500>,
    void,
    TContext
  >;
}
