/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  CreateStatementMutationResponse,
  CreateStatement404,
  CreateStatement500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const createStatementMutationKey = () =>
  [{ url: "/connections/statements" }] as const;

export type CreateStatementMutationKey = ReturnType<
  typeof createStatementMutationKey
>;

/**
 * {@link /connections/statements}
 */
export async function createStatement(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CreateStatementMutationResponse,
    ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
    unknown
  >({ method: "POST", url: `/connections/statements`, ...requestConfig });
  return res.data;
}

export function createStatementMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = createStatementMutationKey();
  return mutationOptions<
    CreateStatementMutationResponse,
    ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return createStatement(config);
    },
  });
}

/**
 * {@link /connections/statements}
 */
export function useCreateStatement<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateStatementMutationResponse,
      ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createStatementMutationKey();

  const baseOptions = createStatementMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateStatementMutationResponse,
    ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
    void,
    TContext
  >;

  return useMutation<
    CreateStatementMutationResponse,
    ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateStatementMutationResponse,
    ResponseErrorConfig<CreateStatement404 | CreateStatement500>,
    void,
    TContext
  >;
}
