/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  CommitConnectionMutationResponse,
  CommitConnection404,
  CommitConnection500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const commitConnectionMutationKey = () =>
  [{ url: "/connections/commit" }] as const;

export type CommitConnectionMutationKey = ReturnType<
  typeof commitConnectionMutationKey
>;

/**
 * {@link /connections/commit}
 */
export async function commitConnection(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CommitConnectionMutationResponse,
    ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
    unknown
  >({ method: "POST", url: `/connections/commit`, ...requestConfig });
  return res.data;
}

export function commitConnectionMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = commitConnectionMutationKey();
  return mutationOptions<
    CommitConnectionMutationResponse,
    ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return commitConnection(config);
    },
  });
}

/**
 * {@link /connections/commit}
 */
export function useCommitConnection<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CommitConnectionMutationResponse,
      ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? commitConnectionMutationKey();

  const baseOptions = commitConnectionMutationOptions(
    config,
  ) as UseMutationOptions<
    CommitConnectionMutationResponse,
    ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
    void,
    TContext
  >;

  return useMutation<
    CommitConnectionMutationResponse,
    ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CommitConnectionMutationResponse,
    ResponseErrorConfig<CommitConnection404 | CommitConnection500>,
    void,
    TContext
  >;
}
