/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  CreateConnectionMutationRequest,
  CreateConnectionMutationResponse,
  CreateConnectionPathParams,
  CreateConnection404,
  CreateConnection500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const createConnectionMutationKey = () =>
  [{ url: "/databases/:id/connections" }] as const;

export type CreateConnectionMutationKey = ReturnType<
  typeof createConnectionMutationKey
>;

/**
 * {@link /databases/:id/connections}
 */
export async function createConnection(
  id: CreateConnectionPathParams["id"],
  data?: CreateConnectionMutationRequest,
  config: Partial<RequestConfig<CreateConnectionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateConnectionMutationResponse,
    ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
    CreateConnectionMutationRequest
  >({
    method: "POST",
    url: `/databases/${id}/connections`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createConnectionMutationOptions(
  config: Partial<RequestConfig<CreateConnectionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = createConnectionMutationKey();
  return mutationOptions<
    CreateConnectionMutationResponse,
    ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
    {
      id: CreateConnectionPathParams["id"];
      data?: CreateConnectionMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return createConnection(id, data, config);
    },
  });
}

/**
 * {@link /databases/:id/connections}
 */
export function useCreateConnection<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateConnectionMutationResponse,
      ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
      {
        id: CreateConnectionPathParams["id"];
        data?: CreateConnectionMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateConnectionMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createConnectionMutationKey();

  const baseOptions = createConnectionMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateConnectionMutationResponse,
    ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
    {
      id: CreateConnectionPathParams["id"];
      data?: CreateConnectionMutationRequest;
    },
    TContext
  >;

  return useMutation<
    CreateConnectionMutationResponse,
    ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
    {
      id: CreateConnectionPathParams["id"];
      data?: CreateConnectionMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateConnectionMutationResponse,
    ResponseErrorConfig<CreateConnection404 | CreateConnection500>,
    {
      id: CreateConnectionPathParams["id"];
      data?: CreateConnectionMutationRequest;
    },
    TContext
  >;
}
