/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  CreateDatabaseMutationRequest,
  CreateDatabaseMutationResponse,
  CreateDatabase400,
  CreateDatabase500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const createDatabaseMutationKey = () => [{ url: "/databases" }] as const;

export type CreateDatabaseMutationKey = ReturnType<
  typeof createDatabaseMutationKey
>;

/**
 * {@link /databases}
 */
export async function createDatabase(
  data: CreateDatabaseMutationRequest,
  config: Partial<RequestConfig<CreateDatabaseMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateDatabaseMutationResponse,
    ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
    CreateDatabaseMutationRequest
  >({ method: "POST", url: `/databases`, data: requestData, ...requestConfig });
  return res.data;
}

export function createDatabaseMutationOptions(
  config: Partial<RequestConfig<CreateDatabaseMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = createDatabaseMutationKey();
  return mutationOptions<
    CreateDatabaseMutationResponse,
    ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
    { data: CreateDatabaseMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createDatabase(data, config);
    },
  });
}

/**
 * {@link /databases}
 */
export function useCreateDatabase<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateDatabaseMutationResponse,
      ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
      { data: CreateDatabaseMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateDatabaseMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createDatabaseMutationKey();

  const baseOptions = createDatabaseMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateDatabaseMutationResponse,
    ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
    { data: CreateDatabaseMutationRequest },
    TContext
  >;

  return useMutation<
    CreateDatabaseMutationResponse,
    ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
    { data: CreateDatabaseMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateDatabaseMutationResponse,
    ResponseErrorConfig<CreateDatabase400 | CreateDatabase500>,
    { data: CreateDatabaseMutationRequest },
    TContext
  >;
}
