/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  DeleteDatabaseMutationResponse,
  DeleteDatabasePathParams,
  DeleteDatabase404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const deleteDatabaseMutationKey = () =>
  [{ url: "/databases/:id" }] as const;

export type DeleteDatabaseMutationKey = ReturnType<
  typeof deleteDatabaseMutationKey
>;

/**
 * {@link /databases/:id}
 */
export async function deleteDatabase(
  id: DeleteDatabasePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteDatabaseMutationResponse,
    ResponseErrorConfig<DeleteDatabase404>,
    unknown
  >({ method: "DELETE", url: `/databases/${id}`, ...requestConfig });
  return res.data;
}

export function deleteDatabaseMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteDatabaseMutationKey();
  return mutationOptions<
    DeleteDatabaseMutationResponse,
    ResponseErrorConfig<DeleteDatabase404>,
    { id: DeleteDatabasePathParams["id"] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteDatabase(id, config);
    },
  });
}

/**
 * {@link /databases/:id}
 */
export function useDeleteDatabase<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteDatabaseMutationResponse,
      ResponseErrorConfig<DeleteDatabase404>,
      { id: DeleteDatabasePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteDatabaseMutationKey();

  const baseOptions = deleteDatabaseMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteDatabaseMutationResponse,
    ResponseErrorConfig<DeleteDatabase404>,
    { id: DeleteDatabasePathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteDatabaseMutationResponse,
    ResponseErrorConfig<DeleteDatabase404>,
    { id: DeleteDatabasePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteDatabaseMutationResponse,
    ResponseErrorConfig<DeleteDatabase404>,
    { id: DeleteDatabasePathParams["id"] },
    TContext
  >;
}
