/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  DeleteConnectionMutationResponse,
  DeleteConnection404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const deleteConnectionMutationKey = () =>
  [{ url: "/connections" }] as const;

export type DeleteConnectionMutationKey = ReturnType<
  typeof deleteConnectionMutationKey
>;

/**
 * {@link /connections}
 */
export async function deleteConnection(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteConnectionMutationResponse,
    ResponseErrorConfig<DeleteConnection404>,
    unknown
  >({ method: "DELETE", url: `/connections`, ...requestConfig });
  return res.data;
}

export function deleteConnectionMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteConnectionMutationKey();
  return mutationOptions<
    DeleteConnectionMutationResponse,
    ResponseErrorConfig<DeleteConnection404>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return deleteConnection(config);
    },
  });
}

/**
 * {@link /connections}
 */
export function useDeleteConnection<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteConnectionMutationResponse,
      ResponseErrorConfig<DeleteConnection404>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteConnectionMutationKey();

  const baseOptions = deleteConnectionMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteConnectionMutationResponse,
    ResponseErrorConfig<DeleteConnection404>,
    void,
    TContext
  >;

  return useMutation<
    DeleteConnectionMutationResponse,
    ResponseErrorConfig<DeleteConnection404>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteConnectionMutationResponse,
    ResponseErrorConfig<DeleteConnection404>,
    void,
    TContext
  >;
}
