/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  DeleteStatementMutationResponse,
  DeleteStatement404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const deleteStatementMutationKey = () =>
  [{ url: "/statements" }] as const;

export type DeleteStatementMutationKey = ReturnType<
  typeof deleteStatementMutationKey
>;

/**
 * {@link /statements}
 */
export async function deleteStatement(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteStatementMutationResponse,
    ResponseErrorConfig<DeleteStatement404>,
    unknown
  >({ method: "DELETE", url: `/statements`, ...requestConfig });
  return res.data;
}

export function deleteStatementMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteStatementMutationKey();
  return mutationOptions<
    DeleteStatementMutationResponse,
    ResponseErrorConfig<DeleteStatement404>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return deleteStatement(config);
    },
  });
}

/**
 * {@link /statements}
 */
export function useDeleteStatement<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteStatementMutationResponse,
      ResponseErrorConfig<DeleteStatement404>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteStatementMutationKey();

  const baseOptions = deleteStatementMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteStatementMutationResponse,
    ResponseErrorConfig<DeleteStatement404>,
    void,
    TContext
  >;

  return useMutation<
    DeleteStatementMutationResponse,
    ResponseErrorConfig<DeleteStatement404>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteStatementMutationResponse,
    ResponseErrorConfig<DeleteStatement404>,
    void,
    TContext
  >;
}
