/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  ExecuteStatementQueryMutationResponse,
  ExecuteStatementQuery404,
  ExecuteStatementQuery500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const executeStatementQueryMutationKey = () =>
  [{ url: "/statements/execute" }] as const;

export type ExecuteStatementQueryMutationKey = ReturnType<
  typeof executeStatementQueryMutationKey
>;

/**
 * {@link /statements/execute}
 */
export async function executeStatementQuery(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ExecuteStatementQueryMutationResponse,
    ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
    unknown
  >({ method: "POST", url: `/statements/execute`, ...requestConfig });
  return res.data;
}

export function executeStatementQueryMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = executeStatementQueryMutationKey();
  return mutationOptions<
    ExecuteStatementQueryMutationResponse,
    ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return executeStatementQuery(config);
    },
  });
}

/**
 * {@link /statements/execute}
 */
export function useExecuteStatementQuery<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ExecuteStatementQueryMutationResponse,
      ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? executeStatementQueryMutationKey();

  const baseOptions = executeStatementQueryMutationOptions(
    config,
  ) as UseMutationOptions<
    ExecuteStatementQueryMutationResponse,
    ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
    void,
    TContext
  >;

  return useMutation<
    ExecuteStatementQueryMutationResponse,
    ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ExecuteStatementQueryMutationResponse,
    ResponseErrorConfig<ExecuteStatementQuery404 | ExecuteStatementQuery500>,
    void,
    TContext
  >;
}
