/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  ExecuteStatementUpdateMutationResponse,
  ExecuteStatementUpdate404,
  ExecuteStatementUpdate500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown>(options: UseMutationOptions<TData, TError, TVariables, TContext>) => options;


export const executeStatementUpdateMutationKey = () =>
  [{ url: "/statements/execute_update" }] as const;

export type ExecuteStatementUpdateMutationKey = ReturnType<
  typeof executeStatementUpdateMutationKey
>;

/**
 * {@link /statements/execute_update}
 */
export async function executeStatementUpdate(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ExecuteStatementUpdateMutationResponse,
    ResponseErrorConfig<ExecuteStatementUpdate404 | ExecuteStatementUpdate500>,
    unknown
  >({ method: "POST", url: `/statements/execute_update`, ...requestConfig });
  return res.data;
}

export function executeStatementUpdateMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = executeStatementUpdateMutationKey();
  return mutationOptions<
    ExecuteStatementUpdateMutationResponse,
    ResponseErrorConfig<ExecuteStatementUpdate404 | ExecuteStatementUpdate500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return executeStatementUpdate(config);
    },
  });
}

/**
 * {@link /statements/execute_update}
 */
export function useExecuteStatementUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ExecuteStatementUpdateMutationResponse,
      ResponseErrorConfig<
        ExecuteStatementUpdate404 | ExecuteStatementUpdate500
      >,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? executeStatementUpdateMutationKey();

  const baseOptions = executeStatementUpdateMutationOptions(
    config,
  ) as UseMutationOptions<
    ExecuteStatementUpdateMutationResponse,
    ResponseErrorConfig<ExecuteStatementUpdate404 | ExecuteStatementUpdate500>,
    void,
    TContext
  >;

  return useMutation<
    ExecuteStatementUpdateMutationResponse,
    ResponseErrorConfig<ExecuteStatementUpdate404 | ExecuteStatementUpdate500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ExecuteStatementUpdateMutationResponse,
    ResponseErrorConfig<ExecuteStatementUpdate404 | ExecuteStatementUpdate500>,
    void,
    TContext
  >;
}
