/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionInfoQueryResponse,
  GetConnectionInfo404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getConnectionInfoSuspenseQueryKey = () =>
  [{ url: "/connections/info" }] as const;

export type GetConnectionInfoSuspenseQueryKey = ReturnType<
  typeof getConnectionInfoSuspenseQueryKey
>;

/**
 * {@link /connections/info}
 */
export async function getConnectionInfoSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionInfoQueryResponse,
    ResponseErrorConfig<GetConnectionInfo404>,
    unknown
  >({ method: "GET", url: `/connections/info`, ...requestConfig });
  return res.data;
}

export function getConnectionInfoSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionInfoSuspenseQueryKey();
  return queryOptions<
    GetConnectionInfoQueryResponse,
    ResponseErrorConfig<GetConnectionInfo404>,
    GetConnectionInfoQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionInfoSuspense(config);
    },
  });
}

/**
 * {@link /connections/info}
 */
export function useGetConnectionInfoSuspense<
  TData = GetConnectionInfoQueryResponse,
  TQueryKey extends QueryKey = GetConnectionInfoSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetConnectionInfoQueryResponse,
        ResponseErrorConfig<GetConnectionInfo404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getConnectionInfoSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getConnectionInfoSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetConnectionInfo404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
