/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionInfoQueryResponse,
  GetConnectionInfo404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getConnectionInfoQueryKey = () =>
  [{ url: "/connections/info" }] as const;

export type GetConnectionInfoQueryKey = ReturnType<
  typeof getConnectionInfoQueryKey
>;

/**
 * {@link /connections/info}
 */
export async function getConnectionInfo(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionInfoQueryResponse,
    ResponseErrorConfig<GetConnectionInfo404>,
    unknown
  >({ method: "GET", url: `/connections/info`, ...requestConfig });
  return res.data;
}

export function getConnectionInfoQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionInfoQueryKey();
  return queryOptions<
    GetConnectionInfoQueryResponse,
    ResponseErrorConfig<GetConnectionInfo404>,
    GetConnectionInfoQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionInfo(config);
    },
  });
}

/**
 * {@link /connections/info}
 */
export function useGetConnectionInfo<
  TData = GetConnectionInfoQueryResponse,
  TQueryData = GetConnectionInfoQueryResponse,
  TQueryKey extends QueryKey = GetConnectionInfoQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetConnectionInfoQueryResponse,
        ResponseErrorConfig<GetConnectionInfo404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getConnectionInfoQueryKey();

  const query = useQuery(
    {
      ...getConnectionInfoQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetConnectionInfo404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
