/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionTableSchemaQueryResponse,
  GetConnectionTableSchemaPathParams,
  GetConnectionTableSchemaQueryParams,
  GetConnectionTableSchema404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getConnectionTableSchemaQueryKey = (
  table_name: GetConnectionTableSchemaPathParams["table_name"],
  params?: GetConnectionTableSchemaQueryParams,
) =>
  [
    {
      url: "/connections/tables/:table_name/schema",
      params: { table_name: table_name },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetConnectionTableSchemaQueryKey = ReturnType<
  typeof getConnectionTableSchemaQueryKey
>;

/**
 * {@link /connections/tables/:table_name/schema}
 */
export async function getConnectionTableSchema(
  table_name: GetConnectionTableSchemaPathParams["table_name"],
  params?: GetConnectionTableSchemaQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionTableSchemaQueryResponse,
    ResponseErrorConfig<GetConnectionTableSchema404>,
    unknown
  >({
    method: "GET",
    url: `/connections/tables/${table_name}/schema`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getConnectionTableSchemaQueryOptions(
  table_name: GetConnectionTableSchemaPathParams["table_name"],
  params?: GetConnectionTableSchemaQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionTableSchemaQueryKey(table_name, params);
  return queryOptions<
    GetConnectionTableSchemaQueryResponse,
    ResponseErrorConfig<GetConnectionTableSchema404>,
    GetConnectionTableSchemaQueryResponse,
    typeof queryKey
  >({
    enabled: !!table_name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionTableSchema(table_name, params, config);
    },
  });
}

/**
 * {@link /connections/tables/:table_name/schema}
 */
export function useGetConnectionTableSchema<
  TData = GetConnectionTableSchemaQueryResponse,
  TQueryData = GetConnectionTableSchemaQueryResponse,
  TQueryKey extends QueryKey = GetConnectionTableSchemaQueryKey,
>(
  table_name: GetConnectionTableSchemaPathParams["table_name"],
  params?: GetConnectionTableSchemaQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetConnectionTableSchemaQueryResponse,
        ResponseErrorConfig<GetConnectionTableSchema404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getConnectionTableSchemaQueryKey(table_name, params);

  const query = useQuery(
    {
      ...getConnectionTableSchemaQueryOptions(table_name, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetConnectionTableSchema404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
