/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionObjectsQueryResponse,
  GetConnectionObjectsQueryParams,
  GetConnectionObjects404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getConnectionObjectsQueryKey = (
  params?: GetConnectionObjectsQueryParams,
) => [{ url: "/connections/objects" }, ...(params ? [params] : [])] as const;

export type GetConnectionObjectsQueryKey = ReturnType<
  typeof getConnectionObjectsQueryKey
>;

/**
 * {@link /connections/objects}
 */
export async function getConnectionObjects(
  params?: GetConnectionObjectsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionObjectsQueryResponse,
    ResponseErrorConfig<GetConnectionObjects404>,
    unknown
  >({ method: "GET", url: `/connections/objects`, params, ...requestConfig });
  return res.data;
}

export function getConnectionObjectsQueryOptions(
  params?: GetConnectionObjectsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionObjectsQueryKey(params);
  return queryOptions<
    GetConnectionObjectsQueryResponse,
    ResponseErrorConfig<GetConnectionObjects404>,
    GetConnectionObjectsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionObjects(params, config);
    },
  });
}

/**
 * {@link /connections/objects}
 */
export function useGetConnectionObjects<
  TData = GetConnectionObjectsQueryResponse,
  TQueryData = GetConnectionObjectsQueryResponse,
  TQueryKey extends QueryKey = GetConnectionObjectsQueryKey,
>(
  params?: GetConnectionObjectsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetConnectionObjectsQueryResponse,
        ResponseErrorConfig<GetConnectionObjects404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getConnectionObjectsQueryKey(params);

  const query = useQuery(
    {
      ...getConnectionObjectsQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetConnectionObjects404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
