/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetDatabaseQueryResponse,
  GetDatabasePathParams,
  GetDatabase404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDatabaseQueryKey = (id: GetDatabasePathParams["id"]) =>
  [{ url: "/databases/:id", params: { id: id } }] as const;

export type GetDatabaseQueryKey = ReturnType<typeof getDatabaseQueryKey>;

/**
 * {@link /databases/:id}
 */
export async function getDatabase(
  id: GetDatabasePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDatabaseQueryResponse,
    ResponseErrorConfig<GetDatabase404>,
    unknown
  >({ method: "GET", url: `/databases/${id}`, ...requestConfig });
  return res.data;
}

export function getDatabaseQueryOptions(
  id: GetDatabasePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getDatabaseQueryKey(id);
  return queryOptions<
    GetDatabaseQueryResponse,
    ResponseErrorConfig<GetDatabase404>,
    GetDatabaseQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getDatabase(id, config);
    },
  });
}

/**
 * {@link /databases/:id}
 */
export function useGetDatabase<
  TData = GetDatabaseQueryResponse,
  TQueryData = GetDatabaseQueryResponse,
  TQueryKey extends QueryKey = GetDatabaseQueryKey,
>(
  id: GetDatabasePathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDatabaseQueryResponse,
        ResponseErrorConfig<GetDatabase404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getDatabaseQueryKey(id);

  const query = useQuery(
    {
      ...getDatabaseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetDatabase404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
