/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionObjectsQueryResponse,
  GetConnectionObjectsQueryParams,
  GetConnectionObjects404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getConnectionObjectsSuspenseQueryKey = (
  params?: GetConnectionObjectsQueryParams,
) => [{ url: "/connections/objects" }, ...(params ? [params] : [])] as const;

export type GetConnectionObjectsSuspenseQueryKey = ReturnType<
  typeof getConnectionObjectsSuspenseQueryKey
>;

/**
 * {@link /connections/objects}
 */
export async function getConnectionObjectsSuspense(
  params?: GetConnectionObjectsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionObjectsQueryResponse,
    ResponseErrorConfig<GetConnectionObjects404>,
    unknown
  >({ method: "GET", url: `/connections/objects`, params, ...requestConfig });
  return res.data;
}

export function getConnectionObjectsSuspenseQueryOptions(
  params?: GetConnectionObjectsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionObjectsSuspenseQueryKey(params);
  return queryOptions<
    GetConnectionObjectsQueryResponse,
    ResponseErrorConfig<GetConnectionObjects404>,
    GetConnectionObjectsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionObjectsSuspense(params, config);
    },
  });
}

/**
 * {@link /connections/objects}
 */
export function useGetConnectionObjectsSuspense<
  TData = GetConnectionObjectsQueryResponse,
  TQueryKey extends QueryKey = GetConnectionObjectsSuspenseQueryKey,
>(
  params?: GetConnectionObjectsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetConnectionObjectsQueryResponse,
        ResponseErrorConfig<GetConnectionObjects404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getConnectionObjectsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getConnectionObjectsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetConnectionObjects404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
