/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionTableTypesQueryResponse,
  GetConnectionTableTypes404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getConnectionTableTypesSuspenseQueryKey = () =>
  [{ url: "/connections/table-types" }] as const;

export type GetConnectionTableTypesSuspenseQueryKey = ReturnType<
  typeof getConnectionTableTypesSuspenseQueryKey
>;

/**
 * {@link /connections/table-types}
 */
export async function getConnectionTableTypesSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionTableTypesQueryResponse,
    ResponseErrorConfig<GetConnectionTableTypes404>,
    unknown
  >({ method: "GET", url: `/connections/table-types`, ...requestConfig });
  return res.data;
}

export function getConnectionTableTypesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionTableTypesSuspenseQueryKey();
  return queryOptions<
    GetConnectionTableTypesQueryResponse,
    ResponseErrorConfig<GetConnectionTableTypes404>,
    GetConnectionTableTypesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionTableTypesSuspense(config);
    },
  });
}

/**
 * {@link /connections/table-types}
 */
export function useGetConnectionTableTypesSuspense<
  TData = GetConnectionTableTypesQueryResponse,
  TQueryKey extends QueryKey = GetConnectionTableTypesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetConnectionTableTypesQueryResponse,
        ResponseErrorConfig<GetConnectionTableTypes404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getConnectionTableTypesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getConnectionTableTypesSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetConnectionTableTypes404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
