/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  GetConnectionTableTypesQueryResponse,
  GetConnectionTableTypes404,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getConnectionTableTypesQueryKey = () =>
  [{ url: "/connections/table-types" }] as const;

export type GetConnectionTableTypesQueryKey = ReturnType<
  typeof getConnectionTableTypesQueryKey
>;

/**
 * {@link /connections/table-types}
 */
export async function getConnectionTableTypes(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetConnectionTableTypesQueryResponse,
    ResponseErrorConfig<GetConnectionTableTypes404>,
    unknown
  >({ method: "GET", url: `/connections/table-types`, ...requestConfig });
  return res.data;
}

export function getConnectionTableTypesQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getConnectionTableTypesQueryKey();
  return queryOptions<
    GetConnectionTableTypesQueryResponse,
    ResponseErrorConfig<GetConnectionTableTypes404>,
    GetConnectionTableTypesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getConnectionTableTypes(config);
    },
  });
}

/**
 * {@link /connections/table-types}
 */
export function useGetConnectionTableTypes<
  TData = GetConnectionTableTypesQueryResponse,
  TQueryData = GetConnectionTableTypesQueryResponse,
  TQueryKey extends QueryKey = GetConnectionTableTypesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetConnectionTableTypesQueryResponse,
        ResponseErrorConfig<GetConnectionTableTypes404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getConnectionTableTypesQueryKey();

  const query = useQuery(
    {
      ...getConnectionTableTypesQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetConnectionTableTypes404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
