/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type { ListDriversQueryResponse } from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listDriversSuspenseQueryKey = () => [{ url: "/drivers" }] as const;

export type ListDriversSuspenseQueryKey = ReturnType<
  typeof listDriversSuspenseQueryKey
>;

/**
 * {@link /drivers}
 */
export async function listDriversSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListDriversQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/drivers`, ...requestConfig });
  return res.data;
}

export function listDriversSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = listDriversSuspenseQueryKey();
  return queryOptions<
    ListDriversQueryResponse,
    ResponseErrorConfig<Error>,
    ListDriversQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listDriversSuspense(config);
    },
  });
}

/**
 * {@link /drivers}
 */
export function useListDriversSuspense<
  TData = ListDriversQueryResponse,
  TQueryKey extends QueryKey = ListDriversSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListDriversQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listDriversSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...listDriversSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
