/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type { ListDriversQueryResponse } from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listDriversQueryKey = () => [{ url: "/drivers" }] as const;

export type ListDriversQueryKey = ReturnType<typeof listDriversQueryKey>;

/**
 * {@link /drivers}
 */
export async function listDrivers(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListDriversQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/drivers`, ...requestConfig });
  return res.data;
}

export function listDriversQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = listDriversQueryKey();
  return queryOptions<
    ListDriversQueryResponse,
    ResponseErrorConfig<Error>,
    ListDriversQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listDrivers(config);
    },
  });
}

/**
 * {@link /drivers}
 */
export function useListDrivers<
  TData = ListDriversQueryResponse,
  TQueryData = ListDriversQueryResponse,
  TQueryKey extends QueryKey = ListDriversQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListDriversQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listDriversQueryKey();

  const query = useQuery(
    {
      ...listDriversQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
