/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type { ListDatabasesQueryResponse } from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listDatabasesQueryKey = () => [{ url: "/databases" }] as const;

export type ListDatabasesQueryKey = ReturnType<typeof listDatabasesQueryKey>;

/**
 * {@link /databases}
 */
export async function listDatabases(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListDatabasesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/databases`, ...requestConfig });
  return res.data;
}

export function listDatabasesQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = listDatabasesQueryKey();
  return queryOptions<
    ListDatabasesQueryResponse,
    ResponseErrorConfig<Error>,
    ListDatabasesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listDatabases(config);
    },
  });
}

/**
 * {@link /databases}
 */
export function useListDatabases<
  TData = ListDatabasesQueryResponse,
  TQueryData = ListDatabasesQueryResponse,
  TQueryKey extends QueryKey = ListDatabasesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListDatabasesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listDatabasesQueryKey();

  const query = useQuery(
    {
      ...listDatabasesQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
