/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type { ListDatabasesQueryResponse } from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listDatabasesSuspenseQueryKey = () =>
  [{ url: "/databases" }] as const;

export type ListDatabasesSuspenseQueryKey = ReturnType<
  typeof listDatabasesSuspenseQueryKey
>;

/**
 * {@link /databases}
 */
export async function listDatabasesSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListDatabasesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/databases`, ...requestConfig });
  return res.data;
}

export function listDatabasesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = listDatabasesSuspenseQueryKey();
  return queryOptions<
    ListDatabasesQueryResponse,
    ResponseErrorConfig<Error>,
    ListDatabasesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listDatabasesSuspense(config);
    },
  });
}

/**
 * {@link /databases}
 */
export function useListDatabasesSuspense<
  TData = ListDatabasesQueryResponse,
  TQueryKey extends QueryKey = ListDatabasesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListDatabasesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listDatabasesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...listDatabasesSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
