/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  PrepareStatementMutationResponse,
  PrepareStatement404,
  PrepareStatement500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const prepareStatementMutationKey = () =>
  [{ url: "/statements/prepare" }] as const;

export type PrepareStatementMutationKey = ReturnType<
  typeof prepareStatementMutationKey
>;

/**
 * {@link /statements/prepare}
 */
export async function prepareStatement(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PrepareStatementMutationResponse,
    ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
    unknown
  >({ method: "POST", url: `/statements/prepare`, ...requestConfig });
  return res.data;
}

export function prepareStatementMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = prepareStatementMutationKey();
  return mutationOptions<
    PrepareStatementMutationResponse,
    ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return prepareStatement(config);
    },
  });
}

/**
 * {@link /statements/prepare}
 */
export function usePrepareStatement<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PrepareStatementMutationResponse,
      ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? prepareStatementMutationKey();

  const baseOptions = prepareStatementMutationOptions(
    config,
  ) as UseMutationOptions<
    PrepareStatementMutationResponse,
    ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
    void,
    TContext
  >;

  return useMutation<
    PrepareStatementMutationResponse,
    ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PrepareStatementMutationResponse,
    ResponseErrorConfig<PrepareStatement404 | PrepareStatement500>,
    void,
    TContext
  >;
}
