/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  QueryDatabaseIpcMutationRequest,
  QueryDatabaseIpcMutationResponse,
  QueryDatabaseIpcPathParams,
  QueryDatabaseIpc404,
  QueryDatabaseIpc500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const queryDatabaseIpcMutationKey = () =>
  [{ url: "/databases/:id/query" }] as const;

export type QueryDatabaseIpcMutationKey = ReturnType<
  typeof queryDatabaseIpcMutationKey
>;

/**
 * {@link /databases/:id/query}
 */
export async function queryDatabaseIpc(
  id: QueryDatabaseIpcPathParams["id"],
  data: QueryDatabaseIpcMutationRequest,
  config: Partial<RequestConfig<QueryDatabaseIpcMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    QueryDatabaseIpcMutationResponse,
    ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
    QueryDatabaseIpcMutationRequest
  >({
    method: "POST",
    url: `/databases/${id}/query`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function queryDatabaseIpcMutationOptions(
  config: Partial<RequestConfig<QueryDatabaseIpcMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = queryDatabaseIpcMutationKey();
  return mutationOptions<
    QueryDatabaseIpcMutationResponse,
    ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
    {
      id: QueryDatabaseIpcPathParams["id"];
      data: QueryDatabaseIpcMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return queryDatabaseIpc(id, data, config);
    },
  });
}

/**
 * {@link /databases/:id/query}
 */
export function useQueryDatabaseIpc<TContext>(
  options: {
    mutation?: UseMutationOptions<
      QueryDatabaseIpcMutationResponse,
      ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
      {
        id: QueryDatabaseIpcPathParams["id"];
        data: QueryDatabaseIpcMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<QueryDatabaseIpcMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? queryDatabaseIpcMutationKey();

  const baseOptions = queryDatabaseIpcMutationOptions(
    config,
  ) as UseMutationOptions<
    QueryDatabaseIpcMutationResponse,
    ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
    {
      id: QueryDatabaseIpcPathParams["id"];
      data: QueryDatabaseIpcMutationRequest;
    },
    TContext
  >;

  return useMutation<
    QueryDatabaseIpcMutationResponse,
    ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
    {
      id: QueryDatabaseIpcPathParams["id"];
      data: QueryDatabaseIpcMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    QueryDatabaseIpcMutationResponse,
    ResponseErrorConfig<QueryDatabaseIpc404 | QueryDatabaseIpc500>,
    {
      id: QueryDatabaseIpcPathParams["id"];
      data: QueryDatabaseIpcMutationRequest;
    },
    TContext
  >;
}
