/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  QueryConnectionIpcMutationRequest,
  QueryConnectionIpcMutationResponse,
  QueryConnectionIpc404,
  QueryConnectionIpc500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const queryConnectionIpcMutationKey = () =>
  [{ url: "/connections/query" }] as const;

export type QueryConnectionIpcMutationKey = ReturnType<
  typeof queryConnectionIpcMutationKey
>;

/**
 * {@link /connections/query}
 */
export async function queryConnectionIpc(
  data: QueryConnectionIpcMutationRequest,
  config: Partial<RequestConfig<QueryConnectionIpcMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    QueryConnectionIpcMutationResponse,
    ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
    QueryConnectionIpcMutationRequest
  >({
    method: "POST",
    url: `/connections/query`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function queryConnectionIpcMutationOptions(
  config: Partial<RequestConfig<QueryConnectionIpcMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = queryConnectionIpcMutationKey();
  return mutationOptions<
    QueryConnectionIpcMutationResponse,
    ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
    { data: QueryConnectionIpcMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return queryConnectionIpc(data, config);
    },
  });
}

/**
 * {@link /connections/query}
 */
export function useQueryConnectionIpc<TContext>(
  options: {
    mutation?: UseMutationOptions<
      QueryConnectionIpcMutationResponse,
      ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
      { data: QueryConnectionIpcMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<QueryConnectionIpcMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? queryConnectionIpcMutationKey();

  const baseOptions = queryConnectionIpcMutationOptions(
    config,
  ) as UseMutationOptions<
    QueryConnectionIpcMutationResponse,
    ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
    { data: QueryConnectionIpcMutationRequest },
    TContext
  >;

  return useMutation<
    QueryConnectionIpcMutationResponse,
    ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
    { data: QueryConnectionIpcMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    QueryConnectionIpcMutationResponse,
    ResponseErrorConfig<QueryConnectionIpc404 | QueryConnectionIpc500>,
    { data: QueryConnectionIpcMutationRequest },
    TContext
  >;
}
