/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  RollbackConnectionMutationResponse,
  RollbackConnection404,
  RollbackConnection500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const rollbackConnectionMutationKey = () =>
  [{ url: "/connections/rollback" }] as const;

export type RollbackConnectionMutationKey = ReturnType<
  typeof rollbackConnectionMutationKey
>;

/**
 * {@link /connections/rollback}
 */
export async function rollbackConnection(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    RollbackConnectionMutationResponse,
    ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
    unknown
  >({ method: "POST", url: `/connections/rollback`, ...requestConfig });
  return res.data;
}

export function rollbackConnectionMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = rollbackConnectionMutationKey();
  return mutationOptions<
    RollbackConnectionMutationResponse,
    ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return rollbackConnection(config);
    },
  });
}

/**
 * {@link /connections/rollback}
 */
export function useRollbackConnection<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RollbackConnectionMutationResponse,
      ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? rollbackConnectionMutationKey();

  const baseOptions = rollbackConnectionMutationOptions(
    config,
  ) as UseMutationOptions<
    RollbackConnectionMutationResponse,
    ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
    void,
    TContext
  >;

  return useMutation<
    RollbackConnectionMutationResponse,
    ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    RollbackConnectionMutationResponse,
    ResponseErrorConfig<RollbackConnection404 | RollbackConnection500>,
    void,
    TContext
  >;
}
