/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  SetConnectionOptionMutationRequest,
  SetConnectionOptionMutationResponse,
  SetConnectionOption404,
  SetConnectionOption500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const setConnectionOptionMutationKey = () =>
  [{ url: "/connections/options" }] as const;

export type SetConnectionOptionMutationKey = ReturnType<
  typeof setConnectionOptionMutationKey
>;

/**
 * {@link /connections/options}
 */
export async function setConnectionOption(
  data: SetConnectionOptionMutationRequest,
  config: Partial<RequestConfig<SetConnectionOptionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SetConnectionOptionMutationResponse,
    ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
    SetConnectionOptionMutationRequest
  >({
    method: "POST",
    url: `/connections/options`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function setConnectionOptionMutationOptions(
  config: Partial<RequestConfig<SetConnectionOptionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = setConnectionOptionMutationKey();
  return mutationOptions<
    SetConnectionOptionMutationResponse,
    ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
    { data: SetConnectionOptionMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return setConnectionOption(data, config);
    },
  });
}

/**
 * {@link /connections/options}
 */
export function useSetConnectionOption<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SetConnectionOptionMutationResponse,
      ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
      { data: SetConnectionOptionMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SetConnectionOptionMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? setConnectionOptionMutationKey();

  const baseOptions = setConnectionOptionMutationOptions(
    config,
  ) as UseMutationOptions<
    SetConnectionOptionMutationResponse,
    ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
    { data: SetConnectionOptionMutationRequest },
    TContext
  >;

  return useMutation<
    SetConnectionOptionMutationResponse,
    ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
    { data: SetConnectionOptionMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SetConnectionOptionMutationResponse,
    ResponseErrorConfig<SetConnectionOption404 | SetConnectionOption500>,
    { data: SetConnectionOptionMutationRequest },
    TContext
  >;
}
