/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  SetStatementSqlQueryMutationRequest,
  SetStatementSqlQueryMutationResponse,
  SetStatementSqlQuery404,
  SetStatementSqlQuery500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const setStatementSqlQueryMutationKey = () =>
  [{ url: "/statements/sql" }] as const;

export type SetStatementSqlQueryMutationKey = ReturnType<
  typeof setStatementSqlQueryMutationKey
>;

/**
 * {@link /statements/sql}
 */
export async function setStatementSqlQuery(
  data: SetStatementSqlQueryMutationRequest,
  config: Partial<RequestConfig<SetStatementSqlQueryMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SetStatementSqlQueryMutationResponse,
    ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
    SetStatementSqlQueryMutationRequest
  >({
    method: "POST",
    url: `/statements/sql`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function setStatementSqlQueryMutationOptions(
  config: Partial<RequestConfig<SetStatementSqlQueryMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = setStatementSqlQueryMutationKey();
  return mutationOptions<
    SetStatementSqlQueryMutationResponse,
    ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
    { data: SetStatementSqlQueryMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return setStatementSqlQuery(data, config);
    },
  });
}

/**
 * {@link /statements/sql}
 */
export function useSetStatementSqlQuery<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SetStatementSqlQueryMutationResponse,
      ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
      { data: SetStatementSqlQueryMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SetStatementSqlQueryMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? setStatementSqlQueryMutationKey();

  const baseOptions = setStatementSqlQueryMutationOptions(
    config,
  ) as UseMutationOptions<
    SetStatementSqlQueryMutationResponse,
    ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
    { data: SetStatementSqlQueryMutationRequest },
    TContext
  >;

  return useMutation<
    SetStatementSqlQueryMutationResponse,
    ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
    { data: SetStatementSqlQueryMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SetStatementSqlQueryMutationResponse,
    ResponseErrorConfig<SetStatementSqlQuery404 | SetStatementSqlQuery500>,
    { data: SetStatementSqlQueryMutationRequest },
    TContext
  >;
}
