/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/client";
import type {
  SetStatementOptionMutationRequest,
  SetStatementOptionMutationResponse,
  SetStatementOption404,
  SetStatementOption500,
} from "../types.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

// Shim for mutationOptions which is missing in v5
const mutationOptions = <
  TData = unknown,
  TError = unknown,
  TVariables = unknown,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
) => options;

export const setStatementOptionMutationKey = () =>
  [{ url: "/statements/options" }] as const;

export type SetStatementOptionMutationKey = ReturnType<
  typeof setStatementOptionMutationKey
>;

/**
 * {@link /statements/options}
 */
export async function setStatementOption(
  data: SetStatementOptionMutationRequest,
  config: Partial<RequestConfig<SetStatementOptionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SetStatementOptionMutationResponse,
    ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
    SetStatementOptionMutationRequest
  >({
    method: "POST",
    url: `/statements/options`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function setStatementOptionMutationOptions(
  config: Partial<RequestConfig<SetStatementOptionMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = setStatementOptionMutationKey();
  return mutationOptions<
    SetStatementOptionMutationResponse,
    ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
    { data: SetStatementOptionMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return setStatementOption(data, config);
    },
  });
}

/**
 * {@link /statements/options}
 */
export function useSetStatementOption<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SetStatementOptionMutationResponse,
      ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
      { data: SetStatementOptionMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SetStatementOptionMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? setStatementOptionMutationKey();

  const baseOptions = setStatementOptionMutationOptions(
    config,
  ) as UseMutationOptions<
    SetStatementOptionMutationResponse,
    ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
    { data: SetStatementOptionMutationRequest },
    TContext
  >;

  return useMutation<
    SetStatementOptionMutationResponse,
    ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
    { data: SetStatementOptionMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SetStatementOptionMutationResponse,
    ResponseErrorConfig<SetStatementOption404 | SetStatementOption500>,
    { data: SetStatementOptionMutationRequest },
    TContext
  >;
}
